# Generated by Django 5.1.4 on 2025-06-05 06:07

import autoslug.fields
import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
import image_cropping.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journalist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(default=None, max_length=255, null=True, unique=True)),
                ('cat_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='cat_name', unique=True)),
                ('cat_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8, verbose_name='Status')),
                ('order', models.IntegerField(default=None, null=True, unique=True, verbose_name='Order')),
            ],
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat_name', models.CharField(default=None, max_length=255, null=True, unique=True)),
                ('subcat_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='subcat_name', unique=True)),
                ('subcat_tag', models.TextField(default='#trending #latest', null=True, verbose_name='Cat tag')),
                ('subcat_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8, verbose_name='Status')),
                ('order', models.IntegerField(default=None, null=True, unique=True, verbose_name='Order')),
                ('sub_cat', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='post_management.category', verbose_name='Select Cetegory')),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200, null=True, verbose_name='News Head Line')),
                ('des', models.CharField(default=None, max_length=300, null=True, verbose_name='Short Discretion')),
                ('sliderimage', image_cropping.fields.ImageCropField(default=None, max_length=255, null=True, upload_to='blog/', verbose_name='Slider Image (1400X520px)')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, max_length=200, null=True, populate_from='slidercat', unique=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=5, null=True, verbose_name='Order')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slidercat', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='post_management.sub_category', verbose_name='Select Cetegory')),
            ],
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(default=None, max_length=150, null=True, verbose_name='News Head Line')),
                ('post_short_des', models.CharField(default=None, max_length=160, null=True, verbose_name='Short Discretion')),
                ('post_des', ckeditor_uploader.fields.RichTextUploadingField(default='No News', null=True, verbose_name='Long Discretion')),
                ('post_image', image_cropping.fields.ImageCropField(default=None, max_length=255, null=True, upload_to='blog/%Y/%m/%d', verbose_name='News Image (1280X720px)')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, max_length=200, null=True, populate_from='post_title', unique=True)),
                ('post_tag', models.TextField(default='#trending #latest', null=True, verbose_name='News tag')),
                ('is_active', models.BooleanField(default=True, null=True, verbose_name='Latest News')),
                ('Head_Lines', models.BooleanField(default=False, null=True, verbose_name='Head Lines')),
                ('articles', models.BooleanField(default=False, null=True, verbose_name='Articles')),
                ('trending', models.BooleanField(default=False, null=True, verbose_name='Trending')),
                ('BreakingNews', models.BooleanField(default=False, null=True, verbose_name='Breaking News')),
                ('Event', models.BooleanField(default=False, null=True, verbose_name='Upcoming Event')),
                ('Event_date', models.DateField(default=django.utils.timezone.now, verbose_name='Event Start Date')),
                ('Eventend_date', models.DateField(default=django.utils.timezone.now, verbose_name='Event End Date')),
                ('schedule_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Schedule Date')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewcounter', models.IntegerField(default=0, editable=False, null=True, verbose_name='Views')),
                ('post_status', models.IntegerField(default=100, null=True, verbose_name='Counter')),
                ('order', models.IntegerField(default=5, null=True, verbose_name='Order')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('rejected', 'Rejected')], default='active', max_length=8)),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('journalist', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='journalist.journalist')),
                ('post_cat', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='post_management.sub_category', verbose_name='Select Cetegory')),
            ],
        ),
        migrations.CreateModel(
            name='VideoNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type', models.CharField(choices=[('video', 'Video'), ('reel', 'Reel')], default='video', max_length=8, verbose_name='Video Type')),
                ('video_title', models.CharField(default=None, max_length=150, null=True, verbose_name='Title (Lenth 60 Char)')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='video_title', unique=True)),
                ('video_short_des', models.CharField(default=None, max_length=160, null=True, verbose_name='Meta/Short Des')),
                ('video_des', ckeditor_uploader.fields.RichTextUploadingField(default=None, null=True, verbose_name='Video Discretion')),
                ('video_url', models.CharField(default=True, max_length=255, null=True, verbose_name='Youtube Video URL')),
                ('video_thumbnail', image_cropping.fields.ImageCropField(blank=True, default='thumbnail/na.jpg', max_length=255, null=True, upload_to='thumbnail/%Y/%m/%d', verbose_name='Thumbnail (1280X720px)')),
                ('video_tag', models.CharField(default=0, max_length=255, null=True)),
                ('schedule_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Schedule Date')),
                ('video_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewcounter', models.IntegerField(default=0, editable=False, null=True, verbose_name='Views')),
                ('counter', models.IntegerField(default=0, null=True, verbose_name='counter')),
                ('order', models.IntegerField(default=5, null=True, verbose_name='Order')),
                ('Head_Lines', models.BooleanField(default=False, null=True, verbose_name='Head Lines')),
                ('articles', models.BooleanField(default=False, null=True, verbose_name='Articles')),
                ('trending', models.BooleanField(default=False, null=True, verbose_name='Trending')),
                ('BreakingNews', models.BooleanField(default=False, null=True, verbose_name='Breaking News')),
                ('is_active', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('rejected', 'Rejected')], default='active', max_length=8, verbose_name='Status')),
                ('News_Category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='post_management.sub_category', verbose_name='Select Category')),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('journalist', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='journalist.journalist')),
            ],
        ),
    ]
